CONTAINER_NAME='blacklist-v1'
IMAGE_NAME='blacklist:v1'
IMAGE_FILE_NAME='blacklist_v1.tar'
IMAGE_FILE_BACKUP_PATH='/home/avrist/repo/cnc-blacklist/backup'

JDK_IMAGE_NAME='openjdk:17-slim-buster'
JDK_IMAGE_FILE_PATH='./depedencies/openjdk17.tar'

CONTAINER_PORT=8700

DB_CNC_HOST='svrqw16chs02'
DB_CNC_PORT=1433
DB_CNC_NAME='AML'
DB_CNC_USERNAME='uatavristh'
DB_CNC_PASSWORD='p@ssw0rd'

DB_AMSSEC_HOST='10.50.1.150'
DB_AMSSEC_PORT=1433
DB_AMSSEC_NAME='AMSSEC02'
DB_AMSSEC_USERNAME='tableau'
DB_AMSSEC_PASSWORD='tableau2019'

CACHE_REDIS_HOST='SVRQW16GHL01'
CACHE_REDIS_PORT=6379

AMSSEC_SECRET_KEY='ams_prod_key_2021#@'
AMSSEC_ENDPOINT='http://10.50.1.90:7002/security/v1/auth/login'
AMSSEC_USERNAME='U2FsdGVkX19fySvRbrWvPb5BF2ECWIBdgqtXLmJWd9g='
AMSSEC_PASSWORD='U2FsdGVkX1+Wuel/mVrWZ+R6tK6G1O2ZitWT61CqcW6YMW6IbbVylGLZIdlyn1V5'
AMSSEC_PARTNER_CODE='CNC'
AMSSEC_DEVICE_TYPE='WB'

NSSSEC_SECRET_KEY='AvristNssKey#$%'

LDAP_BASE='OU=Avrist Users,DC=avrist,DC=net'
LDAP_URL='LDAP://10.50.1.10'
LDAP_USERNAME='DAPP005@avrist.net'
LDAP_PASSWORD='#Avr!st46$^'